Web feature: 1D jump to sequence and splash page
chfi/waragraph pull request #28
Opened 2024-02-06 04:50 UTC by FontenotZach

Description:  
- New functionality allowing for jumping to sequence on 1D graph has been added and tested with bounds testing.  
- GUI changes were made to both the graph view and the home page.  
- The graph view sidebar now contains two scrollable elements for BED files and controls.  
- The home page now contains simple interface for file input and a sidebar for links.
- Added bootstrap dependency.
- Beautified index.html with VSCode plugin.

Type of changes: 
- Feature
- GUI

Testing: 
- GFA, TSV, and BED file upload produce expected behavior.
- Bounds testing on 1D graph demonstrates no input will fall outside the 1D graph bounds.

Additional notes: 
- New typescript code is commented.
- No new compiler/browser warnings or errors.
- The logo next to 'WaraGraph' on the home page is AI generated and copyright free.  

Concerns:
- Not sure about the color scheme or university affiliation.  I went with UTHSC for now.  
- Not sure how we are versioning this software, so I just wrote 'waragraph web beta' at the bottom.
- Not sure why package-lock.json changed so much for one dependency update. Is this ok?

Screenshots: 
- Here is the home page.
![image](https://github.com/chfi/waragraph/assets/39958234/807dad41-b007-4292-a173-442c6621c1bd)
- Here is the graph page, note that the former input boxes are now read-only.
![image](https://github.com/chfi/waragraph/assets/39958234/4cd11d92-6513-42f5-b5ff-70d876e984bf)

2024-02-06 20:02 UTC, chfi requested changes
Great! Besides the two nitpicks above, another small issue is that the rows in the BED list have the same color when toggled on and off.

Also, this can be a separate PR (and isn't high priority), but it'd be nice if the BED and control panels were resizable.

2024-02-06 20:02 UTC, chfi commented on web/index.html
> +            <img src="icons\logo-2.png" style="margin: 2px;" alt="icon" height="60" width="60">
Path should be `icons/logo-2.png` for portability

2024-02-06 20:02 UTC, chfi commented on web/index.html
> +            <span class="h1 mb-0" style="color: black; font-size: 60px;">WaraGraph</span>
"Waragraph" for consistency (and aesthetics imo)

2024-02-07 10:03 UTC, FontenotZach commented
Thanks for the review! HTML changes are in, but I wasn't sure what you meant about the BED list color and the toggle. Is that all in the BED pane or somewhere else?

2024-02-07 16:37 UTC, chfi approved these changes

2024-02-07 16:37 UTC, merged

2024-02-07 16:39 UTC, chfi commented
> Thanks for the review! HTML changes are in, but I wasn't sure what you meant about the BED list color and the toggle. Is that all in the BED pane or somewhere else?

When clicking on the entries in the BED list, the corresponding annotation visualization is toggled on/off: https://github.com/chfi/waragraph/blob/web/web/ts/sidebar-bed.ts#L376-L408
The CSS is in sidebar-bed.css https://github.com/chfi/waragraph/blob/web/web/sidebar-bed.css#L42-L45